Repository CSID-DGU/2023-1-CECD3-Exit-1, pull requests merged in 2023-12, with the labels that each got.

#81 Develop back search image
  build.gradle
  src/main/java/com/example/exitmedserver/search/controller/SearchController.java
  src/main/java/com/example/exitmedserver/search/dto/SearchGetImageSearchResponseDto.java
  src/main/java/com/example/exitmedserver/search/service/SearchService.java
Labels: 🌟 feat 🌟, 🦝석민🦝

#83 Develop back get max allowed
  src/main/java/com/example/exitmedserver/pill/controller/PillController.java
  src/main/java/com/example/exitmedserver/pill/dto/IngredientDataHolder.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetMaxAllowedRequestDto.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetMaxAllowedResponse.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetMaxAllowedResponseDto.java
  src/main/java/com/example/exitmedserver/pill/entity/Drawer.java
  src/main/java/com/example/exitmedserver/pill/entity/Ingredient.java
  src/main/java/com/example/exitmedserver/pill/entity/MaxIngredient.java
  src/main/java/com/example/exitmedserver/pill/repository/IngredientRepository.java
  src/main/java/com/example/exitmedserver/pill/repository/MaxIngredientRepository.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
Labels: 🌟 feat 🌟, 🦝석민🦝

#85 Develop back fix add to drawer
  src/main/java/com/example/exitmedserver/pill/dto/PillAddDrawerRequestDto.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
Labels: 🔨 fix 🔨, 🦝석민🦝

#86 [fix] 이미지 검색 시 5개의 결과만 반환하도록 수정
  src/main/java/com/example/exitmedserver/search/controller/SearchController.java
  src/main/java/com/example/exitmedserver/search/dto/SearchGetImageSearchResponse.java
  src/main/java/com/example/exitmedserver/search/service/SearchService.java
Labels: 🔨 fix 🔨, 🦝석민🦝

#87 [feat] 중복투약 관련 로직 작성
  app/src/main/java/com/cecd/exitmed/data/model/request/RequestPillCreation.kt
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponsePillDetail.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillCreation/PillCreationTimeAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillCreation/PillCreationTimeFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillCreation/PillCreationViewModel.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillCreationDialog.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailDrugInteractionFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailViewModel.kt
  app/src/main/java/com/cecd/exitmed/util/binding/BindingDialogFragment.kt
  app/src/main/res/drawable/img_image_capture_caution2.jpg
  app/src/main/res/drawable/img_image_caputre_caution.jpg
  app/src/main/res/drawable/shape_border_radius_12.xml
  app/src/main/res/layout/activity_image_capture_caution.xml
  app/src/main/res/layout/activity_pill_detail.xml
  app/src/main/res/layout/fragment_create_pill_drawer_dialog.xml
  app/src/main/res/layout/fragment_pill_creation_time.xml
  app/src/main/res/layout/fragment_pill_detail_drug_interaction.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰

#77 [feat] 약서랍 상세뷰 api 연동
  app/src/main/java/com/cecd/exitmed/data/dataSource/remote/DoseDataSource.kt
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponseDrawerDetail.kt
  app/src/main/java/com/cecd/exitmed/data/repository/DoseRepositoryImpl.kt
  app/src/main/java/com/cecd/exitmed/data/service/DoseService.kt
  app/src/main/java/com/cecd/exitmed/domain/repository/DoseRepository.kt
  app/src/main/java/com/cecd/exitmed/domain/type/DoseTime.kt
  app/src/main/java/com/cecd/exitmed/domain/type/DrawerDetail.kt
  app/src/main/java/com/cecd/exitmed/domain/type/DrawerPill.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/PillDrawerListAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/PillDrawerListFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDrawerDetail/PillDrawerDetailActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDrawerDetail/PillDrawerDetailDoseTimeAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDrawerDetail/PillDrawerDetailInfoFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDrawerDetail/PillDrawerDetailMemoFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDrawerDetail/PillDrawerDetailPillInfoFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDrawerDetail/PillDrawerDetailViewModel.kt
  app/src/main/res/layout/activity_pill_drawer_detail.xml
  app/src/main/res/layout/fragment_pill_drawer_detail_info.xml
  app/src/main/res/layout/fragment_pill_drawer_detail_memo.xml
  app/src/main/res/layout/fragment_pill_drawer_detail_pill_info.xml
  app/src/main/res/layout/item_pill_drawer_detail_dose_time.xml
  app/src/main/res/layout/view_toolbar.xml
Labels: 🌟 feat 🌟, 🐰 다은 🐰

#76 [feat] 복용 알림 on/off api 연동
  app/src/main/java/com/cecd/exitmed/data/dataSource/remote/DoseDataSource.kt
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponseOnOffDoseAlarm.kt
  app/src/main/java/com/cecd/exitmed/data/repository/DoseRepositoryImpl.kt
  app/src/main/java/com/cecd/exitmed/data/service/DoseService.kt
  app/src/main/java/com/cecd/exitmed/domain/repository/DoseRepository.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/DoseViewModel.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/PillDrawerListAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/PillDrawerListFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchViewModel.kt
  app/src/main/res/layout/item_my_pill_drawer.xml
Labels: 🌟 feat 🌟, 🐰 다은 🐰
