Repository CSID-DGU/2023-1-CECD3-Exit-1, pull requests merged in 2023-09, with the labels that each got.

#30 [feat] 약 상세뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cecd/exitmed/presentation/common/PillListAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/my/MyPillListActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillCreation/PillCreationActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailComponentsContentFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailDURFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailDrugInteractionFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailMedicationFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailPagerAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailUsageFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchBookmarkAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchBookmarkFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchHistoryAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchHistoryFragment.kt
  app/src/main/res/color/selector_pill_detail_color.xml
  app/src/main/res/drawable/background_speech_bubble.xml
  app/src/main/res/drawable/ic_exclamation_mark.xml
  app/src/main/res/drawable/ic_heart_bookmark.xml
  app/src/main/res/drawable/ic_pill_drawer.xml
  app/src/main/res/drawable/ic_question_mark.xml
  app/src/main/res/drawable/selector_pill_detail_tab.xml
  app/src/main/res/drawable/shape_radius_12.xml
  app/src/main/res/layout/activity_pill_detail.xml
  app/src/main/res/layout/fragment_pill_detail_components_content.xml
  app/src/main/res/layout/fragment_pill_detail_drug_interaction.xml
  app/src/main/res/layout/fragment_pill_detail_dur.xml
  app/src/main/res/layout/fragment_pill_detail_medication.xml
  app/src/main/res/layout/fragment_pill_detail_usage.xml
  app/src/main/res/layout/item_search_bookmark.xml
  app/src/main/res/layout/item_search_history.xml
  app/src/main/res/values/strings.xml
Labels: 🌟 feat 🌟, 🐰 다은 🐰

#35 Develop back signup
  src/main/java/com/example/exitmedserver/user/auth/PrincipalDetails.java
  src/main/java/com/example/exitmedserver/user/auth/PrincipalDetailsService.java
  src/main/java/com/example/exitmedserver/user/controller/UserController.java
  src/main/java/com/example/exitmedserver/user/dto/UserCheckDuplicatedRequestDto.java
  src/main/java/com/example/exitmedserver/user/dto/UserCheckDuplicatedResponseDto.java
  src/main/java/com/example/exitmedserver/user/dto/UserLoginRequestDto.java
  src/main/java/com/example/exitmedserver/user/entity/User.java
  src/main/java/com/example/exitmedserver/user/repository/UserRepository.java
  src/main/java/com/example/exitmedserver/user/service/UserService.java
  src/main/java/com/example/exitmedserver/util/auth/JwtAuthenticationFilter.java
  src/main/java/com/example/exitmedserver/util/auth/JwtAuthorizationFilter.java
  src/main/java/com/example/exitmedserver/util/auth/JwtConfig.java
  src/main/java/com/example/exitmedserver/util/auth/JwtProvider.java
  src/main/java/com/example/exitmedserver/util/auth/JwtTokenInfo.java
  src/main/java/com/example/exitmedserver/util/config/SecurityConfig.java
Labels: ➕ add ➕, 🦝석민🦝

#36 [add] text search 기능 구현. text를 포함하고 있는 경우에도 검색 가능하도록 구현.
  src/main/java/com/example/exitmedserver/search/controller/SearchController.java
  src/main/java/com/example/exitmedserver/search/dto/SearchTextRequestDto.java
  src/main/java/com/example/exitmedserver/search/dto/SearchTextResponseDto.java
  src/main/java/com/example/exitmedserver/search/service/SearchService.java
Labels: ➕ add ➕, 🌟 feat 🌟, 🦝석민🦝

#37 Develop back get favorite
  src/main/java/com/example/exitmedserver/search/controller/SearchController.java
  src/main/java/com/example/exitmedserver/search/dto/SearchAddFavoriteRequestDto.java
  src/main/java/com/example/exitmedserver/search/dto/SearchGetFavoriteResponseDto.java
  src/main/java/com/example/exitmedserver/search/dto/SearchGetSearchListResponse.java
  src/main/java/com/example/exitmedserver/search/entity/FavoriteList.java
  src/main/java/com/example/exitmedserver/search/repository/FavoriteListRepository.java
  src/main/java/com/example/exitmedserver/search/service/SearchService.java
  src/main/java/com/example/exitmedserver/util/auth/JwtAuthorizationFilter.java
Labels: ➕ add ➕, 🌟 feat 🌟, 🦝석민🦝

#39 [feat] #38 최근 검색 기록 추가 기능 구현
  src/main/java/com/example/exitmedserver/search/controller/SearchController.java
  src/main/java/com/example/exitmedserver/search/entity/SearchHistoryList.java
  src/main/java/com/example/exitmedserver/search/repository/SearchHistoryListRepository.java
  src/main/java/com/example/exitmedserver/search/service/SearchService.java
Labels: ➕ add ➕, 🌟 feat 🌟, 🦝석민🦝

#43 [feat] 텍스트 검색, 최근 기록 api 연동
  app/src/main/java/com/cecd/exitmed/data/dataSource/local/ExitLocalDataSource.kt
  app/src/main/java/com/cecd/exitmed/data/dataSource/remote/TextSearchDataSource.kt
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponseRecentSearchTerm.kt
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponseTextSearchList.kt
  app/src/main/java/com/cecd/exitmed/data/repository/TextSearchRepositoryImpl.kt
  app/src/main/java/com/cecd/exitmed/data/service/TextSearchService.kt
  app/src/main/java/com/cecd/exitmed/di/RepositoryModule.kt
  app/src/main/java/com/cecd/exitmed/di/ServiceModule.kt
  app/src/main/java/com/cecd/exitmed/domain/repository/TextSearchRepository.kt
  app/src/main/java/com/cecd/exitmed/domain/type/SearchPill.kt
  app/src/main/java/com/cecd/exitmed/presentation/common/PillListAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/my/MyPillListActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchHistoryFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchViewModel.kt
  app/src/main/java/com/cecd/exitmed/util/binding/BindingAdapter.kt
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_pill.xml
  build.gradle
Labels: 🌟 feat 🌟, 🐰 다은 🐰

#46 [feat] 북마크 api를 임시로 연동합니다.
  app/src/main/java/com/cecd/exitmed/data/dataSource/remote/BookmarkDataSource.kt
  app/src/main/java/com/cecd/exitmed/data/model/request/RequestBookmark.kt
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponseBookmark.kt
  app/src/main/java/com/cecd/exitmed/data/repository/BookmarkRepositoryImpl.kt
  app/src/main/java/com/cecd/exitmed/data/service/BookmarkService.kt
  app/src/main/java/com/cecd/exitmed/di/RepositoryModule.kt
  app/src/main/java/com/cecd/exitmed/di/ServiceModule.kt
  app/src/main/java/com/cecd/exitmed/domain/repository/BookmarkRepository.kt
  app/src/main/java/com/cecd/exitmed/presentation/common/PillListAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/my/MyPillListActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchViewModel.kt
Labels: 🌟 feat 🌟, 🐰 다은 🐰

#50 [feat] #49 약서랍 리스트 가져오기 기능 구현
  src/main/java/com/example/exitmedserver/pill/controller/PillController.java
  src/main/java/com/example/exitmedserver/pill/entity/Alarm.java
  src/main/java/com/example/exitmedserver/pill/repository/AlarmRepository.java
  src/main/java/com/example/exitmedserver/pill/repository/DrawerRepository.java
  src/main/java/com/example/exitmedserver/pill/repository/PillImageRepository.java
  src/main/java/com/example/exitmedserver/pill/repository/PillRepository.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
Labels: 🌟 feat 🌟, 🦝석민🦝

#52 Develop back get drawer detail info
  src/main/java/com/example/exitmedserver/pill/controller/PillController.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetPillInDrawerResponse.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetPillInDrawerResponseDto.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
Labels: 🌟 feat 🌟, 🦝석민🦝

#54 Develop back toggle alarm
  src/main/java/com/example/exitmedserver/pill/controller/PillController.java
  src/main/java/com/example/exitmedserver/pill/dto/PillToggleAlarmResponseDto.java
  src/main/java/com/example/exitmedserver/pill/repository/AlarmRepository.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
Labels: 🌟 feat 🌟, 🦝석민🦝

#56 Develop back get alarm list
  src/main/java/com/example/exitmedserver/pill/controller/PillController.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetAlarmListResponse.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetAlarmListResponseDto.java
  src/main/java/com/example/exitmedserver/pill/repository/AlarmRepository.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
Labels: 🌟 feat 🌟, 🦝석민🦝
