Repository CSID-DGU/2023-1-CECD3-Exit-1, pull requests merged in 2023-10, with the labels that each got.

#59 Develop back get pill detail info
  src/main/java/com/example/exitmedserver/pill/controller/PillController.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetPillDetailInfoResponseDto.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
  src/main/java/com/example/exitmedserver/user/entity/UserProfile.java
  src/main/java/com/example/exitmedserver/user/repository/UserProfileRepository.java
  src/main/java/com/example/exitmedserver/user/service/UserService.java
Labels: 🌟 feat 🌟, 🦝석민🦝

#62 Develop back get closest
  src/main/java/com/example/exitmedserver/pill/controller/PillController.java
  src/main/java/com/example/exitmedserver/pill/dto/PillGetClosestResponseDto.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
Labels: 🌟 feat 🌟, 🦝석민🦝

#65 Develop back add to drawer
  src/main/java/com/example/exitmedserver/pill/dto/PillAddDrawerRequestDto.java
  src/main/java/com/example/exitmedserver/pill/entity/Drawer.java
  src/main/java/com/example/exitmedserver/pill/service/PillService.java
Labels: ➕ add ➕, 🌟 feat 🌟, 🦝석민🦝

#63 [mod] 북마크 시점 수정
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponsePillDetail.kt
  app/src/main/java/com/cecd/exitmed/presentation/common/PillListAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailMedicationFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/pillDetail/PillDetailViewModel.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchActivity.kt
  app/src/main/java/com/cecd/exitmed/presentation/textSearch/SearchViewModel.kt
Labels: 🔮 mod 🔮, 🐰 다은 🐰

#67 [feat] 약서랍 리스트 api 연동
  app/src/main/java/com/cecd/exitmed/data/dataSource/remote/DoseDataSource.kt
  app/src/main/java/com/cecd/exitmed/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponsePillDrawerList.kt
  app/src/main/java/com/cecd/exitmed/data/repository/DoseRepositoryImpl.kt
  app/src/main/java/com/cecd/exitmed/data/service/DoseyService.kt
  app/src/main/java/com/cecd/exitmed/di/RepositoryModule.kt
  app/src/main/java/com/cecd/exitmed/di/ServiceModule.kt
  app/src/main/java/com/cecd/exitmed/domain/repository/DoseRepository.kt
  app/src/main/java/com/cecd/exitmed/domain/type/PillDrawerData.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/DoseViewModel.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/PillDrawerListAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/PillDrawerListFragment.kt
  app/src/main/res/drawable/ic_pill_drawer.xml
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/fragment_pill_drawer.xml
  app/src/main/res/layout/item_my_pill_drawer.xml
  app/src/main/res/values/strings.xml
Labels: 🌟 feat 🌟, 🐰 다은 🐰

#68 [feat] 복용 시간표 api 연동
  app/src/main/java/com/cecd/exitmed/data/dataSource/remote/DoseDataSource.kt
  app/src/main/java/com/cecd/exitmed/data/model/response/ResponseDoseTimeTable.kt
  app/src/main/java/com/cecd/exitmed/data/repository/DoseRepositoryImpl.kt
  app/src/main/java/com/cecd/exitmed/data/service/DoseService.kt
  app/src/main/java/com/cecd/exitmed/di/ServiceModule.kt
  app/src/main/java/com/cecd/exitmed/domain/repository/DoseRepository.kt
  app/src/main/java/com/cecd/exitmed/domain/type/DoseTimeTable.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/DoseTimeTableAdapter.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/DoseTimeTableFragment.kt
  app/src/main/java/com/cecd/exitmed/presentation/dose/DoseViewModel.kt
  app/src/main/res/layout/item_dose_timetable.xml
Labels: 🌟 feat 🌟, 🐰 다은 🐰
